{% set version = "4.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-huxtable
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/huxtable_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/huxtable/huxtable_{{ version }}.tar.gz
  sha256: 45fd886f658f86deabd08cfa45b687d6281ac8a53156c978e7497b31480ad83e

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-assertthat
    - r-broom
    - r-glue
    - r-memoise
    - r-rlang
    - r-stringr >=1.2.0
    - r-tibble
    - r-tidyselect
  run:
    - r-base
    - r-assertthat
    - r-broom
    - r-glue
    - r-memoise
    - r-rlang
    - r-stringr >=1.2.0
    - r-tibble
    - r-tidyselect

test:
  commands:
    - $R -e "library('huxtable')"           # [not win]
    - "\"%R%\" -e \"library('huxtable')\""  # [win]

about:
  home: https://hughjonesd.github.io/huxtable
  license: MIT
  summary: Like 'xtable', creates styled tables. Export to HTML, LaTeX, 'Word',  'Excel', 'PowerPoint'
    and RTF. Simple, modern interface to manipulate  borders, size, position, captions,
    colours, text styles and number formatting. Table cells can span multiple rows and/or
    columns. Includes  a 'huxreg' function for creation of regression tables, and 'quick_*'  one-liners
    to print data to a new document.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: huxtable
# Title: Easily Create and Style Tables for LaTeX, HTML and Other Formats
# Version: 4.3.0
# Authors@R:  person(given = "David", family = "Hugh-Jones", role = c("aut", "cre"), email = "davidhughjones@gmail.com")
# Author: David Hugh-Jones [aut, cre]
# Maintainer: David Hugh-Jones <davidhughjones@gmail.com>
# Description: Like 'xtable', creates styled tables. Export to HTML, LaTeX, 'Word',  'Excel', 'PowerPoint' and RTF. Simple, modern interface to manipulate  borders, size, position, captions, colours, text styles and number formatting. Table cells can span multiple rows and/or columns. Includes  a 'huxreg' function for creation of regression tables, and 'quick_*'  one-liners to print data to a new document.
# License: MIT + file LICENSE
# URL: https://hughjonesd.github.io/huxtable
# BugReports: https://github.com/hughjonesd/huxtable/issues
# Imports: assertthat, broom, glue, memoise, rlang, stats, stringr (>= 1.2.0), tibble, tidyselect, utils
# Suggests: bookdown, covr, crayon, devtools, dplyr, flextable, ggplot2, httr, knitr, lazyeval, lme4, lmtest, nlme, nnet, officer, openxlsx, psych, rmarkdown, sandwich, scales, testthat, tinytex
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.0
# NeedsCompilation: no
# Packaged: 2018-11-07 10:16:20 UTC; david
# Repository: CRAN
# Date/Publication: 2018-11-07 11:00:02 UTC
