appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ttETfQHte3AbQrZKobm2Yy/gVKgSdGfi9ucMyB6lKS31PN5nFDpfqmD0Um8vjJqwNFUVkeuVBsNrSIffaE+SxqgSPkiR4VKCW88iY9bamgN+EKRk+excG5egpd+MA5bAfa1SNAUS+f8rb3B6Z2sJen4MYwJDKhu4XQcvAqCgDcGxfCjPXvzOV2EJZrFwvWbaM+lYz4rq6D8VETC0cRX8cEc7NtSWyHjOzga4vkb92/nzrePw/C1poUnw7yiHq6I2QHnP41iJNwxg1xNm3lia9VI1fAA2b9bwOIiOb1J9A4xNLnAYc484VGuZkyW6oQQLtCraibIdpZ/bVfWvBFxHVgNGdJWcfU+QgAjoh0E4sIEVZ0Gvz0xebQ0EIGAAuz+3K9IX7pFg6dyRAJrEggWClXPcrp96OTtXJ1iPBrPTLsaTt12GmBQaTIuMBKhrPPnvKt3nFRD5jnTVHUMQxIcUuJq45cgp/pxy8bXRjn0+OgMwcu1ECIreH8oTRafyghfOi8uyl2tPNsIfz1A7/eAexAh5kx/gRPTMGHq3zEEF0/ILJW0cpRXApvZwmrz0BBc1+2T6tO88aSBywHu60iLf1CbG71nQGGKqPyIzLUPJ3dmEub3cu82b25HY5HClELSt15YBqwc8ui8Cswkj4RsIHIY8T8w0ja+UIQ/CMRbzImY=}
